### ISSUE TITLE
Flash size when building a runtime from FlexSPI

### ISSUE THREAD

**Issue by 90degs2infty** [imxrt-rs/imxrt-rt#10]
When building a runtime using the [`RuntimeBuilder::from_flexspi` method](https://docs.rs/imxrt-rt/latest/imxrt_rt/struct.RuntimeBuilder.html#method.from_flexspi), does the specified `flash_size` correspond with the flash size that is specified via [`ConfigurationBlock::flash_size`](https://imxrt-rs.github.io/imxrt-boot-gen/imxrt_boot_gen/flexspi/struct.ConfigurationBlock.html#method.flash_size) when setting up a FlexSPI config block? If yes, then why does this size have to be specified twice (i.e. why can't it be extracted from the fcb)? If no, what size does the former refer to?

Thanks for some clarification! 😃

**Comment by mciantyre** [comment]
In practice, they can take the same value. But I'll claim that they're not always the same. They have different purposes, at least today.

- The `flash_size` argument to `RuntimeBuilder::from_flexspi` is a property of a program. The linker uses this value to ensure all of our instructions and data fit in flash. Once we load our program into flash, the value no longer exists.
- The flash size of a FlexSPI configuration block is a property of a board-storage pairing. The MCU uses this value to understand how much storage capacity is available in our flash chip. Unlike the previous value, this value can be found in a program on flash. I'll call this `flash_capacity` to differentiate it from `flash_size`.

Some hypothetical use-cases for different values:

- By specifying `flash_size < flash_capacity`, we could use `flash_capacity - flash_size` bytes for persistent data. (*Ignoring whole-chip erasure, sector size and alignment details, etc.*)
- We're loading `N` separate programs into flash, and we want to ensure that they can all fit. We average `flash_size` for each program to `flash_capacity / N`. Now, our linker tells us if any program takes up too much of its allocation.

Happy to answer any follow-on questions.
